# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '11.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.x'
          channel: 'stable'
      - name: check flutter environments
        run: flutter upgrade --force
      - run: flutter doctor
      - run: flutter clean
      - name: get flutter  
        run: flutter pub get
      - name: build APK
        run: flutter build apk -v

      # delete old artifacts to save money
      - name: Remove artifacts
        uses: c-hive/gha-remove-artifacts@v1.2.0
        with: 
          # Keep the specified number of artifacts even if they are older than the age.
          skip-recent: 2
          age: '2 day'
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/

